//! Embeds every `scenes/*.ron` file into the binary at compile time.
//!
//! Runtime directory scanning (`std::fs::read_dir`) is unavailable in the
//! browser (wasm) build, so we generate a `SCENES` table of
//! `(name, file contents)` pairs that both native and web load from. The
//! contents are pulled in with `include_str!` so editing a scene still triggers
//! a rebuild (see the `rerun-if-changed` line below).

use std::{env, fs, path::PathBuf};

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let scenes_dir = PathBuf::from(&manifest_dir).join("scenes");

    // Rebuild if a scene is added, removed, or edited.
    println!("cargo:rerun-if-changed={}", scenes_dir.display());

    let mut scenes: Vec<(String, PathBuf)> = fs::read_dir(&scenes_dir)
        .unwrap_or_else(|e| panic!("reading {}: {e}", scenes_dir.display()))
        .filter_map(|entry| entry.ok().map(|e| e.path()))
        .filter(|p| p.extension().is_some_and(|ext| ext == "ron"))
        .map(|path| {
            let stem = path
                .file_stem()
                .and_then(|s| s.to_str())
                .expect("scene file name is valid UTF-8")
                .to_string();
            (stem, path)
        })
        .collect();
    // Stable order matches the old filename sort the gallery relied on.
    scenes.sort_by(|a, b| a.0.cmp(&b.0));

    let mut out = String::from(
        "// @generated by build.rs — embedded scene table.\n\
         pub static SCENES: &[(&str, &str)] = &[\n",
    );
    for (stem, path) in &scenes {
        // Absolute path keeps include_str! independent of OUT_DIR's location.
        out.push_str(&format!(
            "    ({stem:?}, include_str!({:?})),\n",
            path.display().to_string()
        ));
        println!("cargo:rerun-if-changed={}", path.display());
    }
    out.push_str("];\n");

    let dest = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR")).join("scene_manifest.rs");
    fs::write(&dest, out).unwrap_or_else(|e| panic!("writing {}: {e}", dest.display()));
}
